name: Build Action
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.21.5
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.8.0'

      - name: Install Qrepo
        run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/nthnn/Qrepo/master/support/install.sh)"

      - name: Build Offion
        run: qrepo run dist

      - name: Check build output
        run: |
          ls dist -ral
          find dist | sort | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"